# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alef < Formula
  desc 'Opinionated polyglot binding generator for Rust libraries'
  homepage 'https://github.com/kreuzberg-dev/alef'
  version '0.4.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-apple-darwin.tar.gz'
      sha256 "c1932c5349fa1fa9889ee5556d751591cdf16c45821b7ffbe83fac43d4c0c208"

      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-x86_64-unknown-linux-gnu.tar.gz'
      sha256 "c1932c5349fa1fa9889ee5556d751591cdf16c45821b7ffbe83fac43d4c0c208"
      define_method(:install) do
        bin.install 'alef'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-unknown-linux-gnu.tar.gz'
      sha256 "c1932c5349fa1fa9889ee5556d751591cdf16c45821b7ffbe83fac43d4c0c208"
      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  test do
    system "#{bin}/alef", '--help'
  end
end

bottle do
  root_url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.8.2'
  sha256 cellar: :any_skip_relocation, arm64_sequoia: 'd489769644152c7eca97311e1b5c3f709c7f82f35272c7fe5946996268ff9f3d'
end

bottle do
  root_url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.11.23'
  sha256 cellar: :any_skip_relocation, arm64_sequoia: 'ce2067706b1c628ffaa09eeb1e52d0b085d2ea92f68482249bb132ef7c70a2ba'
end

bottle do
  root_url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.14.33'
  sha256 cellar: :any_skip_relocation, arm64_sequoia: '30c5b591a918a836e3a5785ef378a4a1a7f8e6ebdc9cef93b74911dcacdee747'
end

  bottle do
    root_url "https://github.com/kreuzberg-dev/alef/releases/download/v0.15.57"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "e85155147454d5dfe1f6d35b3aa5d0bd5722ce67b4dabaad2adea038976ea158"
  end